//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiarioProducao.Classes.PopUp.Turno {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiarioProducao.Classes.PopUp.Turno.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  tabela.serie
        ///     ,  tabela.codigo
        ///	 ,  tabela.descricao
        ///  FROM  OPENQUERY
        ///  (
        ///    {0}
        ///  , &apos; SELECT  lor_man_turno.num_serie_lmtrn              AS serie
        ///           ,  UPPER ( TRIM ( lor_man_turno.cod_turno ) ) AS codigo
        ///           ,  UPPER ( TRIM ( lor_man_turno.den_turno ) ) AS descricao
        ///        FROM  lor_man_empresa
        ///		INNER JOIN lor_man_turno
        ///		  ON  lor_man_turno.num_serie_lme = lor_man_empresa.num_serie_lme
        ///        WHERE lor_man_empresa.cod_empresa =&apos;&apos;{1}&apos;&apos;
        ///		ORDER BY codigo
        ///	&apos;
        ///  ) AS tabela.
        /// </summary>
        internal static string PopUp {
            get {
                return ResourceManager.GetString("PopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnos de Trabalho.
        /// </summary>
        internal static string TabDescription {
            get {
                return ResourceManager.GetString("TabDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lor_etq_linha.
        /// </summary>
        internal static string TabName {
            get {
                return ResourceManager.GetString("TabName", resourceCulture);
            }
        }
    }
}
