//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiarioProducao.Classes.Producao {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiarioProducao.Classes.Producao.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///  FROM OPENQUERY
        ///  (
        ///    {0}
        ///  , &apos;
        ///      SELECT  lor_man_producao.num_serie_lmp
        ///        FROM  lor_man_producao
        ///        WHERE lor_man_producao.num_serie_lmp = {1}
        ///    &apos;
        ///  ).
        /// </summary>
        internal static string DeleteRecord {
            get {
                return ResourceManager.GetString("DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  tabela.existe
        ///  FROM  OPENQUERY
        ///  (
        ///    {0}
        ///  , &apos;
        ///      SELECT  DISTINCT 1 AS existe
        ///        FROM  lor_man_producao
        ///        WHERE lor_man_producao.num_serie_lme   = {1}
        ///        AND   lor_man_producao.dat_inicio      = &quot;{2}&quot;
        ///        AND   lor_man_producao.num_serie_lmtrn = {3}
        ///        AND   lor_man_producao.num_serie_lmlm  = {4}
        ///    &apos;
        ///  ) AS tabela.
        /// </summary>
        internal static string ExisteAk {
            get {
                return ResourceManager.GetString("ExisteAk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  tabela.existe
        ///  FROM  OPENQUERY
        ///  (
        ///    {0}
        ///  , &apos;
        ///      SELECT  DISTINCT 1 AS existe
        ///        FROM  lor_man_producao_observacao
        ///        WHERE lor_man_producao_observacao.num_serie_lmp = {1}
        ///    &apos;
        ///  ) AS tabela.
        /// </summary>
        internal static string ExisteDependencias {
            get {
                return ResourceManager.GetString("ExisteDependencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  tabela.existe
        ///  FROM  OPENQUERY
        ///  (
        ///    {0}
        ///  , &apos;
        ///      SELECT  DISTINCT 1 AS existe
        ///        FROM  lor_man_producao
        ///        WHERE lor_man_producao.num_serie_lmp = {1}
        ///    &apos;
        ///  ) AS tabela.
        /// </summary>
        internal static string ExistePk {
            get {
                return ResourceManager.GetString("ExistePk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  AND   lor_man_producao.dat_inicio &gt;= &quot;{0}&quot;.
        /// </summary>
        internal static string FiltroDatProducao {
            get {
                return ResourceManager.GetString("FiltroDatProducao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  AND   lor_man_linha_montagem.num_serie_lmlm = {0}.
        /// </summary>
        internal static string FiltroLinhaSerie {
            get {
                return ResourceManager.GetString("FiltroLinhaSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  AND   lor_man_turno.num_serie_lmtrn = {0}.
        /// </summary>
        internal static string FiltroTurnoSerie {
            get {
                return ResourceManager.GetString("FiltroTurnoSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT
        ///  INTO OPENQUERY
        ///  (
        ///    {0}
        ///  , &apos;
        ///      SELECT  lor_man_producao.num_serie_lme
        ///           ,  lor_man_producao.num_serie_lmtrn
        ///           ,  lor_man_producao.num_serie_lmlm
        ///           ,  lor_man_producao.dat_inicio
        ///        FROM  lor_man_producao
        ///    &apos;
        ///  )
        ///  VALUES
        ///  (
        ///    {1}
        ///  , {2}
        ///  , {3}
        ///  , &apos;{4}&apos;
        ///  ).
        /// </summary>
        internal static string InsertRecord {
            get {
                return ResourceManager.GetString("InsertRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  tabela.serie_producao
        ///     ,  CONVERT(varchar, tabela.data_producao, 103) as data_producao
        ///     ,  tabela.turno_serie
        ///     ,  tabela.turno_descricao
        ///     ,  tabela.linha_serie
        ///     ,  tabela.linha_descricao
        ///  FROM  OPENQUERY
        ///  (
        ///    {0}
        ///  ,  &apos;SELECT  lor_man_producao.num_serie_lmp            as serie_producao
        ///           ,  lor_man_producao.dat_inicio               as data_producao
        ///           ,  lor_man_turno.num_serie_lmtrn             as turno_serie
        ///           ,  lor_man_turno.den_turno [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryAdapter {
            get {
                return ResourceManager.GetString("QueryAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  tabela.serie_producao
        ///     ,  tabela.serie_empresa
        ///     ,  tabela.codigo_empresa
        ///     ,  tabela.data_producao
        ///     ,  tabela.serie_turno
        ///     ,  tabela.codigo_turno
        ///     ,  tabela.serie_linha_montagem
        ///     ,  tabela.codigo_linha_montagem
        ///  FROM  OPENQUERY
        ///  (
        ///    {0}
        ///    , &apos;SELECT  lor_man_producao.num_serie_lmp            AS serie_producao
        ///            ,  lor_man_empresa.num_serie_lme             AS serie_empresa
        ///            ,  lor_man_empresa.cod_empresa               AS codigo_empresa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryRecordAk {
            get {
                return ResourceManager.GetString("QueryRecordAk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  tabela.serie_producao
        ///     ,  tabela.serie_empresa
        ///     ,  tabela.codigo_empresa
        ///     ,  tabela.data_producao
        ///     ,  tabela.serie_turno
        ///     ,  tabela.codigo_turno
        ///     ,  tabela.serie_linha_montagem
        ///     ,  tabela.codigo_linha_montagem
        ///  FROM  OPENQUERY
        ///  (
        ///    {0}
        ///    , &apos;SELECT  lor_man_producao.num_serie_lmp            AS serie_producao
        ///            ,  lor_man_empresa.num_serie_lme             AS serie_empresa
        ///            ,  lor_man_empresa.cod_empresa               AS codigo_empresa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryRecordAll {
            get {
                return ResourceManager.GetString("QueryRecordAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  tabela.serie_producao
        ///     ,  tabela.serie_empresa
        ///     ,  tabela.codigo_empresa
        ///     ,  tabela.data_producao
        ///     ,  tabela.serie_turno
        ///     ,  tabela.codigo_turno
        ///     ,  tabela.serie_linha_montagem
        ///     ,  tabela.codigo_linha_montagem
        ///  FROM  OPENQUERY
        ///  (
        ///    {0}
        ///    , &apos;SELECT  lor_man_producao.num_serie_lmp            AS serie_producao
        ///            ,  lor_man_empresa.num_serie_lme             AS serie_empresa
        ///            ,  lor_man_empresa.cod_empresa               AS codigo_empresa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryRecordPk {
            get {
                return ResourceManager.GetString("QueryRecordPk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produção.
        /// </summary>
        internal static string TableDescription {
            get {
                return ResourceManager.GetString("TableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lor_man_producao.
        /// </summary>
        internal static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE  OPENQUERY
        ///  (
        ///    {0}
        ///  , &apos;
        ///      SELECT  lor_man_producao.num_serie_lme AS serie_empresa
        ///           ,  lor_man_producao.dat_inicio    AS data_producao
        ///           ,  lor_man_producao.num_serie_lmtrn AS serie_turno
        ///           ,  lor_man_producao.num_serie_lmlm  AS serie_linha_montagem
        ///        FROM  lor_man_producao
        ///        WHERE lor_man_producao.num_serie_lmp = {1}
        ///    &apos;
        ///  ) 
        ///  SET  serie_empresa        = {2}
        ///    ,  data_producao        = &apos;{3}&apos;
        ///    ,  serie_turno          = {4}
        ///    ,   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateRecord {
            get {
                return ResourceManager.GetString("UpdateRecord", resourceCulture);
            }
        }
    }
}
